//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class scheduleSupportingData {
    
    private scheduleSupportingDataLiveVirusConflict[] liveVirusConflictsField;
    
    private scheduleSupportingDataContraindication[] contraindicationsField;
    
    private scheduleSupportingDataVaccineGroup[] vaccineGroupsField;
    
    private scheduleSupportingDataVaccineGroupMap[] vaccineGroupToAntigenMapField;
    
    private scheduleSupportingDataCvxMap[] cvxToAntigenMapField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("liveVirusConflict", IsNullable=false)]
    public scheduleSupportingDataLiveVirusConflict[] liveVirusConflicts {
        get {
            return this.liveVirusConflictsField;
        }
        set {
            this.liveVirusConflictsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("contraindication", IsNullable=false)]
    public scheduleSupportingDataContraindication[] contraindications {
        get {
            return this.contraindicationsField;
        }
        set {
            this.contraindicationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("vaccineGroup", IsNullable=false)]
    public scheduleSupportingDataVaccineGroup[] vaccineGroups {
        get {
            return this.vaccineGroupsField;
        }
        set {
            this.vaccineGroupsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("vaccineGroupMap", IsNullable=false)]
    public scheduleSupportingDataVaccineGroupMap[] vaccineGroupToAntigenMap {
        get {
            return this.vaccineGroupToAntigenMapField;
        }
        set {
            this.vaccineGroupToAntigenMapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("cvxMap", IsNullable=false)]
    public scheduleSupportingDataCvxMap[] cvxToAntigenMap {
        get {
            return this.cvxToAntigenMapField;
        }
        set {
            this.cvxToAntigenMapField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class scheduleSupportingDataLiveVirusConflict {
    
    private scheduleSupportingDataLiveVirusConflictPrevious previousField;
    
    private scheduleSupportingDataLiveVirusConflictCurrent currentField;
    
    private string conflictBeginIntervalField;
    
    private string minConflictEndIntervalField;
    
    private string conflictEndIntervalField;
    
    /// <remarks/>
    public scheduleSupportingDataLiveVirusConflictPrevious previous {
        get {
            return this.previousField;
        }
        set {
            this.previousField = value;
        }
    }
    
    /// <remarks/>
    public scheduleSupportingDataLiveVirusConflictCurrent current {
        get {
            return this.currentField;
        }
        set {
            this.currentField = value;
        }
    }
    
    /// <remarks/>
    public string conflictBeginInterval {
        get {
            return this.conflictBeginIntervalField;
        }
        set {
            this.conflictBeginIntervalField = value;
        }
    }
    
    /// <remarks/>
    public string minConflictEndInterval {
        get {
            return this.minConflictEndIntervalField;
        }
        set {
            this.minConflictEndIntervalField = value;
        }
    }
    
    /// <remarks/>
    public string conflictEndInterval {
        get {
            return this.conflictEndIntervalField;
        }
        set {
            this.conflictEndIntervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class scheduleSupportingDataLiveVirusConflictPrevious {
    
    private string vaccineTypeField;
    
    private string cvxField;
    
    /// <remarks/>
    public string vaccineType {
        get {
            return this.vaccineTypeField;
        }
        set {
            this.vaccineTypeField = value;
        }
    }
    
    /// <remarks/>
    public string cvx {
        get {
            return this.cvxField;
        }
        set {
            this.cvxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class scheduleSupportingDataLiveVirusConflictCurrent {
    
    private string vaccineTypeField;
    
    private string cvxField;
    
    /// <remarks/>
    public string vaccineType {
        get {
            return this.vaccineTypeField;
        }
        set {
            this.vaccineTypeField = value;
        }
    }
    
    /// <remarks/>
    public string cvx {
        get {
            return this.cvxField;
        }
        set {
            this.cvxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class scheduleSupportingDataContraindication {
    
    private string antigenField;
    
    private string contraindicationLanguageField;
    
    private string conceptField;
    
    private string conceptCodeField;
    
    private string conceptTextField;
    
    private string cvxListField;
    
    /// <remarks/>
    public string antigen {
        get {
            return this.antigenField;
        }
        set {
            this.antigenField = value;
        }
    }
    
    /// <remarks/>
    public string contraindicationLanguage {
        get {
            return this.contraindicationLanguageField;
        }
        set {
            this.contraindicationLanguageField = value;
        }
    }
    
    /// <remarks/>
    public string concept {
        get {
            return this.conceptField;
        }
        set {
            this.conceptField = value;
        }
    }
    
    /// <remarks/>
    public string conceptCode {
        get {
            return this.conceptCodeField;
        }
        set {
            this.conceptCodeField = value;
        }
    }
    
    /// <remarks/>
    public string conceptText {
        get {
            return this.conceptTextField;
        }
        set {
            this.conceptTextField = value;
        }
    }
    
    /// <remarks/>
    public string cvxList {
        get {
            return this.cvxListField;
        }
        set {
            this.cvxListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class scheduleSupportingDataVaccineGroup {
    
    private string nameField;
    
    private string administerFullVaccineGroupField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string administerFullVaccineGroup {
        get {
            return this.administerFullVaccineGroupField;
        }
        set {
            this.administerFullVaccineGroupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class scheduleSupportingDataVaccineGroupMap {
    
    private string nameField;
    
    private string[] antigenField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("antigen")]
    public string[] antigen {
        get {
            return this.antigenField;
        }
        set {
            this.antigenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class scheduleSupportingDataCvxMap {
    
    private string cvxField;
    
    private string shortDescriptionField;
    
    private scheduleSupportingDataCvxMapAssociation[] associationField;
    
    /// <remarks/>
    public string cvx {
        get {
            return this.cvxField;
        }
        set {
            this.cvxField = value;
        }
    }
    
    /// <remarks/>
    public string shortDescription {
        get {
            return this.shortDescriptionField;
        }
        set {
            this.shortDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("association")]
    public scheduleSupportingDataCvxMapAssociation[] association {
        get {
            return this.associationField;
        }
        set {
            this.associationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class scheduleSupportingDataCvxMapAssociation {
    
    private string antigenField;
    
    private string associationBeginAgeField;
    
    private string associationEndAgeField;
    
    /// <remarks/>
    public string antigen {
        get {
            return this.antigenField;
        }
        set {
            this.antigenField = value;
        }
    }
    
    /// <remarks/>
    public string associationBeginAge {
        get {
            return this.associationBeginAgeField;
        }
        set {
            this.associationBeginAgeField = value;
        }
    }
    
    /// <remarks/>
    public string associationEndAge {
        get {
            return this.associationEndAgeField;
        }
        set {
            this.associationEndAgeField = value;
        }
    }
}
